[package]
authors = ["The Tremor Team"]
name = "tremor-codec"
edition = "2021"
description = "Tremor Script Interpreter"
documentation = "https://docs.rs/tremor-script"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/tremor-rs/tremor-runtime"
version = "0.13.0-rc.33"


[dependencies]
tremor-value = { workspace = true }
tremor-common = { workspace = true }
tremor-config = { workspace = true }
tokio = { workspace = true, features = ["full"] }
async-trait = { workspace = true }
error-chain = { workspace = true }
futures = { workspace = true }
simd-json-derive = { workspace = true }
value-trait = { workspace = true }
beef = { workspace = true }
byteorder = { workspace = true }
itoa = { workspace = true }
ryu = { workspace = true }
lexical = { workspace = true }
simdutf8 = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
async-recursion = { workspace = true }

schema_registry_converter = { workspace = true, features = ["futures", "rustls_tls", "avro", "easy"] }

# codecs
reqwest = { workspace = true, features = ["rustls-tls", "rustls-tls-native-roots"] }
csv = { workspace = true }
tremor-influx = { workspace = true }
simd-json = { workspace = true }
apache-avro = { workspace = true, features = ["snappy", "bzip", "xz", "zstandard"] }
#
serde = { workspace = true }
rmp-serde = { workspace = true }
syslog_loose = { workspace = true }
serde_yaml = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
test-case = { workspace = true }
