[package]
name = "tremor-codec"
description = "Tremor Codec definition and Codec implementations"
documentation = "https://docs.rs/tremor-codec"
readme = "README.md"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true


[dependencies]
async-recursion = "1"
async-trait = "0.1"
beef.workspace = true
byteorder = "1.5"
chrono = "0.4"
error-chain.workspace = true
futures.workspace = true
lexical = "7"
itoa = "1"
ryu = "1"
schema_registry_converter = { version = "4.2", default-features = false, features = [
  "futures",
  "rustls_tls",
  "avro",
  "easy",
] }
simd-json-derive.workspace = true
simdutf8 = "0.1"
tremor-value.workspace = true
tremor-common.workspace = true
tremor-config.workspace = true
tokio.workspace = true
uuid = { version = "1.9", features = ["v4"] }
value-trait.workspace = true

# codecs
apache-avro = { version = "0.18", features = [
  "snappy",
  "bzip",
  "xz",
  "zstandard",
] }
csv = "1.3"
rmp-serde = "1.2"
serde.workspace = true
serde_yaml.workspace = true
simd-json.workspace = true
syslog_loose = "0.21"
thiserror.workspace = true
tremor-influx.workspace = true

[dev-dependencies]
proptest = "1.5"
test-case = "3"

[features]
128bit = ["tremor-value/128bit"]
