version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: async-trait
    versions:
    - 0.1.48
  - dependency-name: simd-json
    versions:
    - 0.4.0
  - dependency-name: value-trait
    versions:
    - 0.2.1
  - dependency-name: regex
    versions:
    - 1.4.4
