name-template: 'Tremor v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: 'Features and Enhancements '
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Tremor CLI, API and Scripts'
    labels:
      - 'cli'
      - 'api'
      - 'script'
  - title: 'Connectors, Codec, Ramp and Sink'
    labels:
      - 'connectors'
      - 'codec'
      - 'sink'
      - 'ramp'
      - 'onramp'
      - 'offramp'
  - title: 'Pipeline and Operators'
    labels:
      - 'pipeline'
      - 'operators'      
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Maintenance'
    labels:
      - 'dependencies'
      - 'ci/cd'
      - 'tests'
  - title: 'Documentation'
    label:
      - 'notes'
      - 'documentation'
      - 'docs'
  - title: 'Security'
    label: security  
change-template: '- $TITLE - @$AUTHOR : #$NUMBER'
template: |
  ## What's New
  ## General
  $CHANGES
autolabeler:
  - label: 'notes'
    branch:
      - '/tremor-notes/'
  - label: 'packaging'
    branch:
      - '/packaging/'
  - label: 'codec'
    branch:
      - '/src/codec'
      - '/src/codec.rs'
  - label: 'connectors'
    branch:
      - '/src/connectors'
      - '/src/connectors.rs'
  - label: 'onramps'
    branch:
      - '/src/onramp.rs'
  - label: 'offramps'
    branch:
      - '/src/offramp.rs'
  - label: 'tests'
    branch:
      - '/tests/'
  - label: 'api'
    branch:
      - '/tremor-api/'
  - label: 'cli'
    branch:
      - '/tremor-cli/'
  - label: 'commons'
    branch:
      - '/tremor-commons/'
  - label: 'erl'
    branch:
      - '/tremor-erl/'
  - label: 'influx'
    branch:
      - '/tremor-influx/'
  - label: 
      - 'pipeline'
      - 'operator'    
    branch:
      - '/tremor-pipeline/'
  - label: 'operator'    
    branch:
      - '/tremor-pipeline/src/op'
      - '/tremor-pipeline/src/op.rs'
  - label: 'script'
    branch:
      - '/tremor-script/'
  - label: 'value'
    branch:
      - '/tremor-value/'