kind: pipeline
name: test-on-arm64

platform:
  arch: arm64
  os: linux

steps:
  - name: test
    image: rust:1
    environment:
      RUSTFLAGS: "-C target-cpu=native"
    commands:
      - apt-get -qy update && apt-get install -y libssl-dev libssl1.1 cmake libclang-dev
      - rustup default nightly
      - rustup update
      - cargo +nightly test --verbose --all
