kind: pipeline
name: test-on-arm64

platform:
  arch: arm64

steps:
  - name: test
    image: rust:1
    environment:
      RUSTFLAGS: "-C target-cpu=native"
    commands:
      - sudo apt-get -qy update && sudo apt-get install -y libssl-dev libssl1.1 cmake
      - rustup default nightly
      - rustup update
      - cargo +nightly test --verbose --all
