ignore:
  - "tremor-script/src/ast/support.rs" # This is a pure support file
  - "tremor-script/src/ast/base_expr.rs" # This are only getters
  - "tremor-script/src/registry/custom_fn.rs" # behind a feature flag - not used
  - "http-bench-server/**" # test tool only
  - "**/errors.rs" # lots of error strings
  - "depricated/**" # depricated code, for storage not running - inactive
  - "**/main.rs" # main files are cli entry points
  - "**/args.rs" # Files for clap argument parsing
  - "tremor-api/**" # This is done vie EQC and coytoee tests - sadly they do not count
