FROM rust:1.47.0 as builder

RUN cargo install --features=ssl websocat

FROM tremorproject/tremor:0.9.1

COPY --from=builder /usr/local/cargo/bin/websocat /usr/local/bin/websocat

ENV TREMOR_PATH=/opt/local/tremor/lib

ENTRYPOINT ["/entrypoint.sh"]
