FROM rust:1.49.0 as builder

RUN cargo install --features=ssl websocat

FROM tremorproject/tremor:0.10.0

COPY --from=builder /usr/local/cargo/bin/websocat /usr/local/bin/websocat

# Install workshop related tools
RUN apt-get update \
    && apt-get install -y wget curl netcat  \
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*


ENV TREMOR_PATH=/opt/local/tremor/lib

ENTRYPOINT ["/entrypoint.sh"]
