[package]
name = "tremor-interceptor"
edition = "2021"
authors = ["The Tremor Team"]
description = "Tremor Preprocessors, Postprocessors, and maybe soon: Interceptors"
documentation = "https://docs.tremor.rs"
homepage = "https://www.tremor.rs"
license = "Apache-2.0"
repository = "https://github.com/tremor-rs/tremor-runtime"
version = "0.13.0-rc.33"
rust-version = "1.76"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tremor-value = { workspace = true }
tremor-config = { workspace = true }
tremor-common = { workspace = true }
log = { workspace = true }
serde = { workspace = true, features = ["derive"] }
byteorder = { workspace = true }
value-trait = { workspace = true }
memchr = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }

#gelf
rand = { workspace = true, features = [], optional = true }

# Compression
brotli = { workspace = true, features = ["std"], optional = true }
xz2 = { workspace = true, features = [], optional = true }
lz4 = { workspace = true, features = [], optional = true }
snap = { workspace = true, features = [], optional = true }
zstd = { workspace = true, features = [], optional = true }
libflate = { workspace = true, features = ["std"], optional = true }

# Length Prefix
bytes = { workspace = true, features = [], optional = true }
ringbuf-blocking = { workspace = true, features = ["std"], optional = true }
ringbuf = { workspace = true, features = ["std"], optional = true }


[dev-dependencies]
proptest = { workspace = true }


[features]
default = ["base64", "compression", "gelf", "length-prefix"]
length-prefix = ["dep:bytes"]
gelf = ["dep:rand"]
base64 = []
compression = [
    "dep:brotli",
    "dep:xz2",
    "dep:lz4",
    "dep:snap",
    "dep:zstd",
    "dep:libflate",
    "dep:ringbuf-blocking",
    "dep:ringbuf",
]
