[package]
name = "tremor-connectors-azure"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
tremor-common.workspace = true
tremor-config.workspace = true
tremor-connectors.workspace = true
tremor-script.workspace = true
tremor-system.workspace = true
tremor-value.workspace = true

anyhow.workspace = true
async-trait = "0.1"
azure_core = { version = "0.24", default-features = false, features = [
  "reqwest",
  "reqwest_gzip",
  "reqwest_rustls",
  "tokio",
] }
log.workspace = true
reqwest = { version = "0.12", default-features = false, features = ["json"] }
serde.workspace = true
tokio.workspace = true
url.workspace = true
bytes = "1.10"
futures.workspace = true
serde_json.workspace = true
beef.workspace = true
simd-json.workspace = true
mockito = "1.7.0"

[features]
integration-harness = []
