[package]
name = "tremor-connectors-azure"
edition = "2021"
version = "0.13.0-rc.33"
authors = ["The Tremor Team"]
homepage = "https://www.tremor.rs"
license = "Apache-2.0"

[dependencies]
tremor-connectors = { workspace = true }
tremor-common = { workspace = true }
tremor-system = { workspace = true }
tremor-value = { workspace = true }
tremor-config = { workspace = true }

azure_core = { workspace = true, features = ["enable_reqwest", "enable_reqwest_gzip", "enable_reqwest_rustls"] }
serde = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
url = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
tokio = { workspace = true }
log = { workspace = true }
tremor-script = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true, features = ["alloc", "std", "async-await", "futures-executor"] }
serde_json = { workspace = true }
beef = { workspace = true }
simd-json = { workspace = true }
mockito = { workspace = true }

[features]
integration-harness = []
