# The onramp and offramp sections of configuration specify external sources and sinks
# to an instance of tremor-server.
#
onramp:
  - id: ws-input          # A unique id for binding/mapping
    type: ws              # The unique type descriptor for the onramp ( websocket server here)
    codec: string         # The underlying data format expected for application payload data
    config:
      port: 4242          # The TCP port to listen on
      host: '0.0.0.0'     # The IP address to bind on ( all interfaces in this case )
      
offramp:
  - id: es-output
    type: elastic         # an elastic search offramp
    config:
      endpoints:          # this is the eleastic search host started by docker compose
        - http://elastic:9200