[package]
name = "tremor-connectors-aws"
version = "0.13.0-rc.33"
edition = "2021"
license = "Apache-2.0"
homepage = "https://www.tremor.rs"
authors = ["The Tremor Team"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tremor-connectors = { workspace = true }
tremor-connectors-object-storage = { workspace = true }
tremor-common = { workspace = true }
tremor-system = { workspace = true }
tremor-value = { workspace = true }
tremor-config = { workspace = true }

async-trait = { workspace = true }
serde = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
async-channel = { version = "2", default-features = false }
thiserror = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
simd-json = { workspace = true }
value-trait = { workspace = true }

aws-sdk-s3 = { workspace = true, features = ["behavior-version-latest", "sigv4a", "rustls", "rt-tokio"] }
aws-types = { workspace = true }
aws-config = { workspace = true }
aws-credential-types = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
testcontainers = { workspace = true }
serial_test = { workspace = true }
bytes = { workspace = true }
tremor-connectors-test-helpers = { workspace = true }
testcontainers-modules = { workspace = true, features = ["localstack"] }

[features]
integration-harness = []
