[package]
name = "tremor-connectors-aws"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tremor-common.workspace = true
tremor-connectors.workspace = true
tremor-connectors-object-storage = { path = "../tremor-connectors-object-storage" }
tremor-system.workspace = true
tremor-value.workspace = true
tremor-config.workspace = true

async-trait = { version = "0.1", default-features = false }
serde.workspace = true
anyhow.workspace = true
async-channel = { version = "2", default-features = false }
thiserror.workspace = true
tokio.workspace = true
log.workspace = true
simd-json.workspace = true
value-trait.workspace = true

aws-sdk-s3 = { version = "1", default-features = false, features = [
  "behavior-version-latest",
  "sigv4a",
  "rustls",
  "rt-tokio",
] }
aws-types = { version = "1", default-features = false }
aws-config = { version = "1", default-features = false }
aws-credential-types = { version = "1", default-features = false }

[dev-dependencies]
bytes = { version = "1.6", default-features = true }
env_logger = { version = "0.11", default-features = true }
rand = { version = "0.9", default-features = false }
serial_test = { version = "3.0", default-features = false }
testcontainers = { version = "0.24", default-features = false }
testcontainers-modules = { version = "0.12", features = ["localstack"] }
tremor-connectors-test-helpers = { path = "../tremor-connectors-test-helpers" }

[features]
integration-harness = []
