[package]
name = "dissect"
version = "0.1.0"
authors = ["The Tremor Team"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
halfbrown = "0.1"
simd-json = {version = "0.2", features = ["known-key"]}