onramp:
  - id: in
    type: file
    config:
      source: "{in}"
      close_on_done: true
      sleep_on_done: 500

offramp:
  - id: out
    type: file
    config:
      file: "{out}"

binding:
  - id: test
    links:
      "/onramp/in/{instance}/out": ["/pipeline/query/{instance}/in"]
      "/pipeline/query/{instance}/out": ["/offramp/out/{instance}/in"]
