[package]
name = "tremor-connectors-gcp"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
tremor-connectors.workspace = true
tremor-connectors-object-storage = { path = "../tremor-connectors-object-storage" }
tremor-common.workspace = true
tremor-system.workspace = true
tremor-value.workspace = true
tremor-config.workspace = true
tremor-script.workspace = true

anyhow.workspace = true
async-channel = { version = "2.3", default-features = true }
async-stream = { version = "0.3", default-features = true }
async-trait = { version = "0.1", default-features = true }
bytes = { version = "1.10", default-features = true }
futures.workspace = true
gcloud-sdk = { version = "0.27", default-features = false, features = [
  "tls-roots",
  "google-pubsub-v1",
  "google-cloud-bigquery-storage-v1",
  "google-logging-v2",
  "google-storage-v2",

] }
gouth = { version = "0.2", default-features = true }
hyper = { version = "1.6", default-features = true, features = [
  "server",
  "http1",
  "http2",
] }
hyper-util = { version = "0.1", features = [
  "server",
  "server-graceful",
  "http1",
  "http2",
] }
hyper-rustls = { version = "0.27", default-features = true, features = [
  "rustls-native-certs",
  "http1",
  "http2",
  "native-tokio",
] }
http = { version = "1.3", default-features = true }
http-body-util = "0.1"
log.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
url.workspace = true
simd-json-derive.workspace = true
simd-json.workspace = true

[dev-dependencies]
env_logger = { version = "0.11", default-features = true }
hyper-util = { version = "0.1", features = ["server", "http1", "http2"] }
serial_test = "3.2"
tempfile = { version = "3", default-features = true }
test-case = { version = "3", default-features = true }
testcontainers = { version = "0.24", default-features = true }
testcontainers-modules = { version = "0.12.1", features = [
  "google_cloud_sdk_emulators",
] }
tremor-codec.workspace = true
tremor-connectors-test-helpers = { path = "../tremor-connectors-test-helpers" }
value-trait.workspace = true

[features]
integration-harness = []
