[package]
name = "tremor-connectors-gcp"
version = "0.13.0-rc.33"
edition = "2021"
license = "Apache-2.0"
homepage = "https://www.tremor.rs"
authors = ["The Tremor Team"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tremor-connectors = { workspace = true }
tremor-connectors-object-storage = { workspace = true }
tremor-common = { workspace = true }
tremor-system = { workspace = true }
tremor-value = { workspace = true }
tremor-config = { workspace = true }
tremor-script = { workspace = true }

anyhow = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
http = { version = "0.2", default-features = true }
log = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

bytes = { workspace = true }
googapis = { workspace = true, features = ["google-pubsub-v1", "google-cloud-bigquery-storage-v1", "google-logging-v2", "google-storage-v2"] }
gouth = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true, features = ["transport", "tls"] }
hyper = { version = "0.14", default-features = true, features = [
    "server",
    "http1",
    "http2",
    "runtime",
] }
hyper-rustls = { version = "0.24", default-features = true, features = [
    "rustls-native-certs",
    "http1",
    "http2",
    "tokio-runtime",
] }
url = { workspace = true }
async-channel = { version = "1.9", default-features = true }
async-stream = { workspace = true }
simd-json-derive = { workspace = true }
simd-json = { workspace = true }

[dev-dependencies]
testcontainers = { workspace = true }
hyper = { version = "0.14", default-features = true, features = [
    "server",
    "http1",
    "http2",
    "runtime",
] }
tokio = { workspace = true }
value-trait = { workspace = true }
test-case = { workspace = true }
anyhow = { workspace = true }
tremor-codec = { workspace = true }
tempfile = { workspace = true }
env_logger = { workspace = true }
tremor-connectors-test-helpers = { workspace = true }
serial_test = { workspace = true }
testcontainers-modules = { workspace = true, features = ["google_cloud_sdk_emulators"] }

[features]
integration-harness = []
