<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tremor.proto

namespace Wayfair\Tremor\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>wayfair.tremor.Event</code>
 */
class Event extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.wayfair.tremor.Event.Header header = 1;</code>
     */
    private $header = null;
    /**
     * Generated from protobuf field <code>bytes body = 2;</code>
     */
    private $body = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Wayfair\Tremor\Proto\Event\Header $header
     *     @type string $body
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Tremor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.wayfair.tremor.Event.Header header = 1;</code>
     * @return \Wayfair\Tremor\Proto\Event\Header
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>.wayfair.tremor.Event.Header header = 1;</code>
     * @param \Wayfair\Tremor\Proto\Event\Header $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Wayfair\Tremor\Proto\Event_Header::class);
        $this->header = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes body = 2;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Generated from protobuf field <code>bytes body = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, False);
        $this->body = $var;

        return $this;
    }

}

