<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tremor.proto

namespace Wayfair\Tremor\Proto;

if (false) {
    /**
     * This class is deprecated. Use Wayfair\Tremor\Proto\Event\Header\ContentType instead.
     * @deprecated
     */
    class Event_Header_ContentType {}
}
class_exists(Event\Header\ContentType::class);
@trigger_error('Wayfair\Tremor\Proto\Event_Header_ContentType is deprecated and will be removed in the next major release. Use Wayfair\Tremor\Proto\Event\Header\ContentType instead', E_USER_DEPRECATED);

