# Example minimal config, also used in docker images
# please do not change!
---

# Scan this file for changes every 30 seconds
refresh_rate: 30 seconds

appenders:
  # An appender named "stdout" that writes to stdout
  stdout:
    kind: console

  # An appender named "requests" that writes to a file with a custom pattern encoder
  file:
    kind: file
    path: "/logs/tremor.log"
    encoder:
      pattern: "{d} - {m}{n}"

# Write only warnings to stdout
root:
  level: error
  appenders:
    - stdout

loggers:
  # Write info level logs to the log file
  tremor_runtime:
    level: info
    appenders:
      - file
    additive: false

