# Scan this file for changes every 30 seconds
refresh_rate: 30 seconds

appenders:
  # An appender named "stdout" that writes to stdout
  stdout:
    kind: console

root:
  level: warn
  appenders:
    - stdout

loggers:
  tremor_runtime:
    level: info
    appenders:
      - stdout
    additive: false
  tremor:
    level: info
    appenders:
      - stdout
    additive: false
