[package]
name = "tremor-archive"
description = "Tremor Archive"
readme = "README.md"
authors.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
log.workspace = true
serde.workspace = true
serde_json.workspace = true
simd-json.workspace = true
sha2 = "0.10"
thiserror = "2"
tokio.workspace = true
tokio-tar = "0.3"
tokio-stream = "0.1"

tremor-common.workspace = true
tremor-script.workspace = true
