[package]
name = "tremor-archive"
authors = ["The Tremor Team"]
description = "Tremor Runtime"
documentation = "https://docs.tremor.rs"
edition = "2021"
homepage = "https://www.tremor.rs"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/tremor-rs/tremor-runtime"
version = "0.13.0-rc.33"

[dependencies]
tremor-common = { workspace = true }
tremor-script = { workspace = true }

tokio = { workspace = true, features = [] }
tokio-tar = { workspace = true }
tokio-stream = { workspace = true }
thiserror = { workspace = true }
sha2 = { workspace = true }
simd-json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
log = { workspace = true }
serde_json = { workspace = true }
