[package]
authors = ["The Tremor Team"]
description = "Tremor CLI Tool"
edition = "2021"
license = "Apache-2.0"
name = "tremor-cli"
version = "0.13.0-rc.33"
homepage = "https://www.tremor.rs"

[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"

[build-dependencies]
lalrpop = { workspace = true }
matches = { workspace = true }

[dev-dependencies]
temp-dir = { workspace = true }
criterion = { workspace = true }
float-cmp = { workspace = true }
matches = { workspace = true }
pretty_assertions = { workspace = true }

[dependencies]
tokio = { workspace = true, features = ["full"] }
anyhow = { workspace = true }
clap = { workspace = true, features = ["color", "derive"] }
clap_complete = { workspace = true }
difference = { workspace = true }
env_logger = { workspace = true }
futures = { workspace = true }
halfbrown = { workspace = true }
http-types = { workspace = true }
log = { workspace = true }
log4rs = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
signal-hook = { workspace = true }
signal-hook-tokio = { workspace = true, features = ["futures-v0_3"] }
simd-json = { workspace = true, features = ["known-key"] }
# We need to stay with 0.2 for now as there are reasons that can be named for the need to be able to
# compile and run on operating systems that are a decade old. (insert apropriate ammount rage)
snmalloc-rs = { workspace = true }
surf = { version = "=2.3.2", default-features = false, features = [
  "encoding",
  "h1-client-rustls",
  "middleware-logger",
] }
tremor-api = { workspace = true }
tremor-codec = { workspace = true }
tremor-interceptor = { workspace = true }
tremor-common = { workspace = true }
tremor-pipeline = { workspace = true }
tremor-runtime = { workspace = true }
tremor-script = { workspace = true }
tremor-value = { workspace = true }
tremor-system = { workspace = true }
tremor-archive = { workspace = true }
url = { workspace = true }
error-chain = { workspace = true }
globwalk = { workspace = true }
port_scanner = { workspace = true }
shell-words = { workspace = true }
tch = { workspace = true, optional = true }
termcolor = { workspace = true }

[[bin]]
name = "tremor"
path = "src/main.rs"
test = false

[features]
#
# We use *empty* feature dependencies so that we can switch allocators
# via feature flags. We *require* no default features so that that mechanism
# in src/alloc.rs works effectively in practice.
#
# It is an error to configure defaults in tremor.cli at this time until rust
# allows switching allocators at compile time - this is currently not well
# supported via the global_allocator attribute nor via cfg attributes that
# levarage features
#

snmalloc = []
bert = ["tremor-runtime/bert", "tch"]
default = []
stdalloc = []
