[package]
name = "tremor-connectors-otel"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tremor-connectors.workspace = true
tremor-common.workspace = true
tremor-system.workspace = true
tremor-value.workspace = true
tremor-config.workspace = true
tremor-script.workspace = true

anyhow.workspace = true
async-trait = { version = "0.1", default-features = true }
log.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
simd-json.workspace = true

# opentelemetry
tonic = { version = "0.6.1", default-features = false, features = [
  "transport",
  "tls",
] }
# prost = { version = "0.9.0", default-features = false }
# prost-types = { version = "0.9.0", default-features = false }
# This is related to https://github.com/tremor-rs/tremor-runtime/issues/1688 the otel API's need to
# be updated together with tonic
tremor-otelapis = { version = "=0.2.4", default-features = false, features = [
  "otel-all",
] }
rand.workspace = true
async-channel = { version = "1.9", default-features = false }
hex = { version = "0.4", default-features = false, features = ["alloc", "std"] }

[dev-dependencies]
proptest = "1.6"
test-case = "3"

[features]
integration-harness = []
