[package]
name = "tremor-connectors-otel"
version = "0.13.0-rc.33"
edition = "2021"
license = "Apache-2.0"
homepage = "https://www.tremor.rs"
authors = ["The Tremor Team"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tremor-connectors = { workspace = true }
tremor-common = { workspace = true }
tremor-system = { workspace = true }
tremor-value = { workspace = true }
tremor-config = { workspace = true }
tremor-script = { workspace = true }

anyhow = { workspace = true }
async-trait = { workspace = true }
# futures = { version = "0.3", default-features = true }
# http = { version = "0.2", default-features = true }
# http-body = { version = "1.0", default-features = true }
log = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
# value-trait = { version = "0.8", default-features = true }
tokio = { workspace = true }
simd-json = { workspace = true }

# opentelemetry
tonic = { workspace = true, features = ["transport", "tls"] }
# prost = { version = "0.9.0", default-features = false }
# prost-types = { version = "0.9.0", default-features = false }
# This is related to https://github.com/tremor-rs/tremor-runtime/issues/1688 the otel API's need to
# be updated together with tonic
tremor-otelapis = { workspace = true, features = ["otel-all"] }
rand = { workspace = true }
async-channel = { version = "1.9", default-features = false }
hex = { workspace = true, features = ["alloc", "std"] }

[dev-dependencies]
tokio = { workspace = true }
proptest = { workspace = true }
test-case = { workspace = true }

[features]
integration-harness = []
