[package]
name = "tremor-connectors"
version = "0.13.0-rc.33"
edition = "2021"
license = "Apache-2.0"
homepage = "https://www.tremor.rs"
authors = ["The Tremor Team"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tremor-common = { workspace = true }
tremor-config = { workspace = true }
tremor-codec = { workspace = true }
tremor-pipeline = { workspace = true }
tremor-script = { workspace = true }
tremor-value = { workspace = true }
tremor-interceptor = { workspace = true }
tremor-system = { workspace = true }
tokio = { workspace = true }
beef = { workspace = true }
value-trait = { workspace = true }
futures = { workspace = true, features = ["std"] }
halfbrown = { workspace = true }
simd-json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
url = { workspace = true }
async-trait = { workspace = true }
log = { workspace = true, features = ["kv_unstable"] }
tokio-stream = { workspace = true }
bimap = { workspace = true, features = ["serde", "std"] }
hostname = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
event-listener = { workspace = true }
lazy_static = { workspace = true }
either = { workspace = true, features = ["serde"] }
rand = { workspace = true }

# shared
simd-json-derive = { workspace = true, optional = true }
uuid = { workspace = true, features = ["v4"], optional = true }
hyper = { version = "1.3.1", optional = true, default-features = false, features = [
    "server",
    "http1",
    "http2",
] }
hyper-util = { workspace = true, features = ["http1", "http2", "client", "client-legacy", "tokio", "server-auto"], optional = true }
gouth = { workspace = true, optional = true }


# tls
tokio-rustls = { workspace = true, optional = true }
rustls = { workspace = true, optional = true }
rustls-pemfile = { workspace = true, optional = true }
rustls-native-certs = { workspace = true, optional = true }

# dns
trust-dns-resolver = { workspace = true, features = ["tokio-runtime", "system-config"], optional = true }

# elasticsearch
elasticsearch = { workspace = true, features = ["rustls-tls"], optional = true }

# http
http = { version = "1.1", optional = true, default-features = false }
hyper-rustls = { version = "0.27", optional = true, default-features = false, features = [
    "rustls-native-certs",
    "http1",
    "http2",
    "ring",
] }
http-body-util = { workspace = true, optional = true }
mime = { workspace = true, optional = true }
base64 = { workspace = true, optional = true }
dashmap = { workspace = true, optional = true }
async-stream = { workspace = true, optional = true }

# kafka
rdkafka = { workspace = true, features = ["cmake-build", "libz-static", "tokio"], optional = true }
rdkafka-sys = { workspace = true, features = ["cmake-build", "libz-static"], optional = true }
indexmap = { workspace = true, optional = true }

# websockets
tokio-tungstenite = { workspace = true, features = ["handshake"], optional = true }

# discord
serenity = { workspace = true, features = ["client", "gateway", "rustls_backend", "model", "cache"], optional = true }

# file
file-mode = { workspace = true, optional = true }
async-compression = { workspace = true, features = ["xz", "tokio"], optional = true }

# kv
sled = { workspace = true, optional = true }

qwal = { workspace = true, features = ["tokio"], optional = true } # wal

# bench
hdrhistogram = { workspace = true, optional = true }
xz2 = { workspace = true, optional = true }


# clickhouse
clickhouse-rs = { workspace = true, features = ["tokio_io", "tls"], optional = true }
# Clickhouse chrono-tz is out of date so we ringfence it here. Hopefully a new version will be released soon...
clickhouse-chrono-tz = { workspace = true, optional = true }

# crononome
serde_yaml = { workspace = true, optional = true }
chrono = { workspace = true, optional = true }
cron = { workspace = true, optional = true }

# udp
socket2 = { workspace = true, optional = true }

[dev-dependencies]
serde_yaml = { workspace = true }
test-case = { workspace = true }
proptest = { workspace = true }
testcontainers = { workspace = true }
serial_test = { workspace = true }
http-types = { workspace = true }
bytes = { workspace = true }
tempfile = { workspace = true }
env_logger = { workspace = true }
tremor-connectors-test-helpers = { workspace = true }
tide = { workspace = true } # TODO remove tide from TestHttpServer
tokio = { workspace = true, features = ["full", "test-util"] }

[features]
default = [
    "dns",
    "elasticsearch",
    "http",
    "kafka",
    "websocket",
    "discord",
    "file",
    "kv",
    "wal",
    "clickhouse",
    "crononome",
    "stdio",
    "metronome",
    "null",
    "metrics",
    "tcp",
    "udp",
    "unix-socket",
    "dev",
    "integration-harness-local",
]

128bit = ["tremor-value/128bit"]
mime = []
socket = ["dep:socket2"]

dev = ["circut-breaker", "exit", "bench"]

tls = [
    "dep:hyper",
    "dep:rustls-native-certs",
    "dep:rustls-pemfile",
    "dep:rustls",
    "dep:tokio-rustls",
]

dns = ["dep:trust-dns-resolver"]
elasticsearch = ["dep:elasticsearch", "dep:serde_yaml", "tls", "http"]
http = [
    "dep:base64",
    "dep:dashmap",
    "dep:gouth",
    "dep:http",
    "dep:http-body-util",
    "dep:hyper-rustls",
    "dep:hyper-util",
    "dep:hyper",
    "dep:mime",
    "dep:async-stream",
    "hyper/http1",
    "hyper/http2",
    "tls",
    "mime",
    "socket",
]

kafka = ["dep:rdkafka", "dep:rdkafka-sys", "dep:indexmap"]
websocket = ["dep:tokio-tungstenite", "tls", "socket"]
discord = ["dep:serenity"]
file = ["dep:file-mode", "dep:async-compression"]
kv = ["dep:sled"]
wal = ["dep:qwal", "dep:simd-json-derive"]
bench = ["dep:xz2", "dep:hdrhistogram"]
clickhouse = ["dep:clickhouse-rs", "dep:clickhouse-chrono-tz", "dep:uuid"]
crononome = ["dep:serde_yaml", "dep:chrono", "dep:cron"]
stdio = []
metronome = []
null = []
metrics = []
exit = []
circut-breaker = []
tcp = ["socket", "tls"]
udp = ["socket"]
unix-socket = ["socket", "dep:file-mode"]

integration-harness = [
    "integration-harness-docker",
    "integration-harness-local",
]
integration-harness-docker = [
    "integration-tests-clickhouse",
    "integration-tests-elasticsearch",
    "integration-tests-kafka",
]
integration-harness-local = [
    "integration-tests-bench",
    "integration-tests-crononome",
    "integration-tests-file",
    "integration-tests-http",
    "integration-tests-metronome",
    "integration-tests-tcp",
    "integration-tests-udp",
    "integration-tests-unix-socket",
    "integration-tests-wal",
    "integration-tests-websocket",
]

# enable flaky tests
flaky-test = []

integration-tests-bench = ["bench"]
integration-tests-clickhouse = ["clickhouse", "dep:chrono"]
integration-tests-crononome = ["crononome"]
integration-tests-elasticsearch = ["elasticsearch"]
integration-tests-file = ["file"]
integration-tests-http = ["http"]
integration-tests-kafka = ["kafka"]
integration-tests-metronome = ["metronome"]
integration-tests-tcp = ["tcp"]
integration-tests-udp = ["udp"]
integration-tests-unix-socket = ["unix-socket"]
integration-tests-wal = ["wal"]
integration-tests-websocket = ["websocket"]
