#!/bin/sh

set -x

. $(dirname $0)/common.inc

BENCH_EXTRA?=""

file=$1
if [ ! -f $file ]
then
  file="./bench/$file.yaml"
fi

if [ "${TREMOR_DEV_ENV}" = "devcontainer" ]
then
  TARGET_ROOT=target.vsc
else
  TARGET_ROOT=target
fi

if [ "${TREMOR_MODE}" = "debug" ]
then
  TARGET_MODE=debug
else
  TARGET_MODE=release
fi

if [ ! -f $file ]
then
    echo "Benchmark file ./bench/$1.yaml not found!"
    exit 1
fi

echo "######## $1"

echo "TARGET_ROOT: ${TARGET_ROOT}"

if [ -d ./bench/$1 ]
then
  ${BENCH_EXTRA} ${TARGET_ROOT}/${TARGET_MODE}/tremor-server --no-api -c $file bench/link.yaml --query ./bench/$1/*.trickle
else
  ${BENCH_EXTRA} ${TARGET_ROOT}/${TARGET_MODE}/tremor-server --no-api -c $file bench/link.yaml
fi
