#!/bin/sh

. $(dirname $0)/common.inc

if [ ! -f ./bench/$1.yaml ]
then
    echo "Benchmark file ./bench/$1.yaml not found!"
    exit 1
fi
result=$(target/release/tremor-server -c ./bench/$1.yaml -m ./bench/link.yaml -q 20)

echo "$result"
