# Blaster side of the WS benchmark
---
onramp:
  - id: ws-in
    type: ws
    codec: json
    config:
      host: 127.0.0.1
      port: 4242

offramp:
  - id: blackhole
    type: blackhole
    codec: json
    config:
      warmup_secs: 10
      stop_after_secs: 40
      significant_figures: 2


binding:
  - id: ws-blaster
    links:
      '/onramp/ws-in/{instance}/out': [ '/pipeline/main/{instance}/in' ]
      '/pipeline/main/{instance}/out': [ '/offramp/blackhole/{instance}/in' ]

pipeline:
  - id: main
    interface:
      inputs:
        - in
      outputs:
        - out
    links:
      in: [ out ]

  
mapping:
  /binding/ws-blaster/01:
    instance: "01"