<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tremor.proto

namespace Wayfair\Tremor\Proto\Event;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>wayfair.tremor.Event.Header</code>
 */
class Header extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.wayfair.tremor.Event.Header.ContentType content_type = 1;</code>
     */
    private $content_type = 0;
    /**
     * Generated from protobuf field <code>bytes uuid = 2;</code>
     */
    private $uuid = '';
    /**
     * Generated from protobuf field <code>bytes parent_uuid = 3;</code>
     */
    private $parent_uuid = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $content_type
     *     @type string $uuid
     *     @type string $parent_uuid
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Tremor::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.wayfair.tremor.Event.Header.ContentType content_type = 1;</code>
     * @return int
     */
    public function getContentType()
    {
        return $this->content_type;
    }

    /**
     * Generated from protobuf field <code>.wayfair.tremor.Event.Header.ContentType content_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setContentType($var)
    {
        GPBUtil::checkEnum($var, \Wayfair\Tremor\Proto\Event_Header_ContentType::class);
        $this->content_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes uuid = 2;</code>
     * @return string
     */
    public function getUuid()
    {
        return $this->uuid;
    }

    /**
     * Generated from protobuf field <code>bytes uuid = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUuid($var)
    {
        GPBUtil::checkString($var, False);
        $this->uuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes parent_uuid = 3;</code>
     * @return string
     */
    public function getParentUuid()
    {
        return $this->parent_uuid;
    }

    /**
     * Generated from protobuf field <code>bytes parent_uuid = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setParentUuid($var)
    {
        GPBUtil::checkString($var, False);
        $this->parent_uuid = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Header::class, \Wayfair\Tremor\Proto\Event_Header::class);

