onramp:
  - id: gelf-tcp
    # TODO make this tcp later
    type: tcp2
    preprocessors:
      - lines-null
      - remove-empty
    codec: json
    config:
      # TODO support strings here
      #host: 'localhost'
      host: 127.0.0.1
      port: 12202
      # TODO introduce config option for delimiter (null byte for gelf tcp)

offramp:
  - id: console
    type: stdout
    codec: json
    config:
      prefix: 'GELF (TCP): '

binding:
  - id: gelf-tcp
    links:
      '/onramp/gelf-tcp/{instance}/out': [ '/pipeline/main/{instance}/in' ]
      '/pipeline/main/{instance}/out': [ '/offramp/console/{instance}/in' ]
      '/pipeline/main/{instance}/error': [ '/offramp/system::stderr/{instance}/in' ]

mapping:
  /binding/gelf-tcp/01:
    instance: '01'

pipeline:
  - id: main
    interface:
      inputs:
        - in
      outputs:
        - out
        - error
    nodes:
      - id: runtime
        op: runtime::tremor
        config:
          script: |
            match event of
              # if timestamp is not set by clients:
              # http://docs.graylog.org/en/latest/pages/gelf.html#gelf-payload-specification
              case %{absent timestamp} =>
                let event.timestamp = system::ingest_ns() / 1000000000
              default =>
                null
            end;

            # add source info to the event via pipeline variables (passed from the tcp onramp)
            let event = patch event of
              upsert "source_id" => $source_id,
              upsert "source_ip" => $source_ip,
              upsert "source_port" => $source_port
            end;

            event;
    links:
      in: [ runtime ]
      runtime: [ out ]
      runtime/error: [ error ]
