onramp:
  - id: gelf-udp
    type: udp
    preprocessors:
      - decompress
      - gelf-chunking
      - decompress
    codec: json
    config:
      host: 127.0.0.1
      port: 12202

offramp:
  - id: console
    type: stdout
    config:
      prefix: 'GELF (UDP): '

binding:
  - id: gelf-udp
    links:
      '/onramp/gelf-udp/{instance}/out': [ '/pipeline/main/{instance}/in' ]
      '/pipeline/main/{instance}/out': [ '/offramp/console/{instance}/in' ]
      '/pipeline/main/{instance}/error': [ '/offramp/system::stderr/{instance}/in' ]

mapping:
  /binding/gelf-udp/01:
    instance: '01'

pipeline:
  - id: main
    interface:
      inputs:
        - in
      outputs:
        - out
        - error
    nodes:
      - id: runtime
        op: runtime::tremor
        config:
          script: |
            match event of
              # if timestamp is not set by clients:
              # http://docs.graylog.org/en/latest/pages/gelf.html#gelf-payload-specification
              case %{absent timestamp} =>
                let event.timestamp = system::ingest_ns() / 1000000000
              default =>
                null
            end;
            event;
    links:
      in: [ runtime ]
      runtime: [ out ]
      runtime/error: [ error ]
