onramp:
  - id: tcp
    type: tcp
    preprocessors:
      - lines-pipe
    codec: string
    config:
      # TODO support strings here
      #host: "localhost"
      host: 127.0.0.1
      port: 9000

offramp:
  - id: console
    type: stdout
    codec: string
    config:
      prefix: "TCP "

binding:
  - id: tcp
    links:
      '/onramp/tcp/{instance}/out': [ '/pipeline/main/{instance}/in' ]
      '/pipeline/main/{instance}/out': [ '/offramp/console/{instance}/in' ]

mapping:
  /binding/tcp/01:
    instance: "01"

pipeline:
  - id: main
    interface:
      inputs:
        - in
      outputs:
        - out
    links:
      in: [ out ]
