[package]
name = "tremor-pipeline"
description = "Tremor Pipeline DAG Runtime"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
tokio.workspace = true
beef.workspace = true
halfbrown.workspace = true
indexmap = "2"
rand.workspace = true
log.workspace = true
lru = "0.14"
petgraph = "0.8"
regex.workspace = true
rust-bert = { version = "0.23.0", optional = true }
serde.workspace = true
serde_yaml.workspace = true
simd-json.workspace = true
simd-json-derive.workspace = true
value-trait.workspace = true
sled = "0.34"
thiserror.workspace = true
tremor-common.workspace = true
tremor-config.workspace = true
tremor-script.workspace = true
tremor-value.workspace = true
tremor-system.workspace = true

url = "2"
fenster = { version = "0.1.1" }

[dev-dependencies]
criterion = "0.6"
tempfile = "3.8"
xz2 = "0.1"
tokio = { version = "1.39", features = ["full"] }

[features]
bert = ["rust-bert"]
