[package]
authors = ["The Tremor Team"]
description = "Tremor Pipeline DAG Runtime"
edition = "2021"
license = "Apache-2.0"
name = "tremor-pipeline"
version = "0.13.0-rc.33"

[dependencies]
tokio = { workspace = true }
beef = { workspace = true, features = ["impl_serde"] }
error-chain = { workspace = true }
halfbrown = { workspace = true }
indexmap = { workspace = true }
rand = { workspace = true, features = ["small_rng"] }
lazy_static = { workspace = true }
log = { workspace = true }
lru = { workspace = true }
petgraph = { workspace = true }
regex = { workspace = true }
rust-bert = { workspace = true, optional = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
simd-json = { workspace = true, features = ["known-key"] }
simd-json-derive = { workspace = true }
value-trait = { workspace = true }
sled = { workspace = true }
tremor-common = { workspace = true }
tremor-config = { workspace = true }
tremor-script = { workspace = true }
tremor-value = { workspace = true }
tremor-system = { workspace = true }

url = { workspace = true }
fenster = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
tempfile = { workspace = true }
xz2 = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[features]
bert = ["rust-bert"]
