<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tremor.proto

namespace Wayfair\Tremor\Proto\Event\Header;

/**
 * Protobuf type <code>wayfair.tremor.Event.Header.ContentType</code>
 */
class ContentType
{
    /**
     * Generated from protobuf enum <code>UNKNOWN = 0;</code>
     */
    const UNKNOWN = 0;
    /**
     * Generated from protobuf enum <code>JSON = 1;</code>
     */
    const JSON = 1;
    /**
     * Generated from protobuf enum <code>MSGPACK = 2;</code>
     */
    const MSGPACK = 2;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ContentType::class, \Wayfair\Tremor\Proto\Event_Header_ContentType::class);

