[package]
name = "tremor-config"
description = "Tremor Config"
documentation = "https://docs.rs/tremor-config"
readme = "README.md"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
tremor-value.workspace = true
serde.workspace = true
