[package]
name = "tremor-system"
version = "0.13.0-rc.33"
edition = "2021"
license = "Apache-2.0"
homepage = "https://www.tremor.rs"
authors = ["The Tremor Team"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tremor-common = { workspace = true }
tremor-script = { workspace = true }

tokio = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
simd-json-derive = { workspace = true }
simd-json = { workspace = true }
either = { workspace = true }

[dev-dependencies]
tremor-value = { workspace = true }
