<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tremor.proto

namespace GPBMetadata;

class Tremor
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa6020a0c7472656d6f722e70726f746f120e776179666169722e747265" .
            "6d6f7222e4010a054576656e74122c0a0668656164657218012001280b32" .
            "1c2e776179666169722e7472656d6f722e4576656e742e48656164657212" .
            "0c0a04626f647918022001280c1a9e010a06486561646572123e0a0c636f" .
            "6e74656e745f7479706518012001280e32282e776179666169722e747265" .
            "6d6f722e4576656e742e4865616465722e436f6e74656e7454797065120c" .
            "0a047575696418022001280c12130a0b706172656e745f75756964180320" .
            "01280c22310a0b436f6e74656e7454797065120b0a07554e4b4e4f574e10" .
            "0012080a044a534f4e1001120b0a074d53475041434b10024217ca021457" .
            "6179666169725c5472656d6f725c50726f746f620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

