version: "3.3"
services:
  zookeeper:
    image: "wurstmeister/zookeeper:3.4.6"
    ports:
      - "2181:2181"
  kafka:
    image: "wurstmeister/kafka:2.12-2.1.1"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "info:1:1,error:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
  elastic:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.6"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
  kibana:
    image: "docker.elastic.co/kibana/kibana:7.17.6"
    ports:
      - "5601:5601"
    depends_on:
      - elastic
    environment:
      ELASTICSEARCH_HOSTS: "http://elastic:9200"
    links:
      - elastic
  influx:
    image: influxdb:2.1
    ports:
      - "8086:8086"
      - "8083:8083"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "tremor"
      DOCKER_INFLUXDB_INIT_PASSWORD: "snotbadger"
      DOCKER_INFLUXDB_INIT_ORG: "tremor"
      DOCKER_INFLUXDB_INIT_BUCKET: "tremor"
      DOCKER_INFLUXDB_INIT_RETENTION: "1d"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "snotbadger"
  tremor:
    image: tremorproject/tremor:latest
    depends_on:
      - kibana
      - kafka
      - influx
    ports:
      - 9898:9898
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=debug
    volumes:
      - ./configs/tremor:/etc/tremor:ro
      - ./logs:/logs:rw
      - ./data:/data:ro
    working_dir: "/"
    command: server run -d -l /etc/tremor/logger.yaml /etc/tremor/config/main.troy
