all: operator-docs preprocessor-docs postprocessor-docs codec-docs

operator-docs: 
	scripts/operators.sh

preprocessor-docs: 
	scripts/preprocessors.sh

postprocessor-docs: 
	scripts/postprocessors.sh

codec-docs: 
	scripts/codecs.sh