<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tremor.proto

namespace Wayfair\Tremor\Proto;

if (false) {
    /**
     * This class is deprecated. Use Wayfair\Tremor\Proto\Event\Header instead.
     * @deprecated
     */
    class Event_Header {}
}
class_exists(Event\Header::class);
@trigger_error('Wayfair\Tremor\Proto\Event_Header is deprecated and will be removed in the next major release. Use Wayfair\Tremor\Proto\Event\Header instead', E_USER_DEPRECATED);

