[package]
authors = ["The Tremor Team"]
build = "build.rs"
description = "Tremor Script Interpreter"
documentation = "https://docs.rs/tremor-script"
edition = "2021"
license = "Apache-2.0"
name = "tremor-script"
readme = "README.md"
repository = "https://github.com/tremor-rs/tremor-runtime"
version = "0.13.0-rc.33"

[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"

# Additional `RUSTFLAGS` to set (default: none)
rustc-args = ["-C target-feature=+avx,+avx2,+sse4.2"]

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
name = "tremor_script"

[dependencies]
atty = { workspace = true }
beef = { workspace = true, features = ["impl_serde"] }
byteorder = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
cidr-utils = { workspace = true }
codespan = { workspace = true }
dissect = { workspace = true }
distance = { workspace = true }
downcast-rs = { workspace = true }
error-chain = { workspace = true }
glob = { workspace = true }
grok = { workspace = true }
sha2 = { workspace = true }
halfbrown = { workspace = true }
hdrhistogram = { workspace = true }
hostname = { workspace = true }
jumphash = { workspace = true }
lalrpop-util = { workspace = true }
lazy_static = { workspace = true }
percent-encoding = { workspace = true }
rand = { workspace = true, features = ["small_rng"] }
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
simd-json = { workspace = true, features = ["known-key"] }
simd-json-derive = { workspace = true }
value-trait = { workspace = true }
sketches-ddsketch = { workspace = true }
strip-ansi-escapes = { workspace = true }
termcolor = { workspace = true }
tremor-common = { workspace = true }
tremor-influx = { workspace = true }
tremor-value = { workspace = true }
tremor-codec = { workspace = true }
tremor-kv = { workspace = true }
unicode-xid = { workspace = true }
url = { workspace = true }
xz2 = { workspace = true }

[build-dependencies]
lalrpop = { workspace = true }
chrono-tz = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
float-cmp = { workspace = true }
pretty_assertions = { workspace = true }
proptest = { workspace = true }
tempfile = { workspace = true }
test-case = { workspace = true }

[features]
# this is required for the erlang EQC tests of the language
erlang-float-testing = []
# This is required for the language server to prevent unbounded growth of the area
arena-delete = []

[[bench]]
name = "array_flatten"
harness = false

[[bench]]
name = "arithmetics"
harness = false
