[package]
description = "Tremor Api Callbacks"
name = "tremor-api"
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true
homepage.workspace = true

[dependencies]
halfbrown = { workspace = true }
http-types = "2"
log = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
simd-json = { workspace = true }
tokio = { workspace = true }
# we don't need sessions or cookies or shitty logging middleware
tide = { version = "0.16", default-features = false, features = ["h1-server"] }
tremor-pipeline = { workspace = true }
tremor-runtime = { workspace = true }
tremor-script = { workspace = true }
tremor-value = { workspace = true }
tremor-common = { workspace = true }
tremor-system = { workspace = true }

[dev-dependencies]
surf = { version = "2.3", default-features = false, features = [
  "h1-client-rustls",
] }
env_logger = "0.11"
