[package]
authors = ["The Tremor Team"]
description = "Tremor Api Callbacks"
edition = "2021"
license = "Apache-2.0"
name = "tremor-api"
version = "0.13.0-rc.33"
homepage = "https://www.tremor.rs"

[dependencies]
halfbrown = { workspace = true }
http-types = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
simd-json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
# we don't need sessions or cookies or shitty logging middleware
tide = { workspace = true, features = ["h1-server"] }
tremor-pipeline = { workspace = true }
tremor-runtime = { workspace = true }
tremor-script = { workspace = true }
tremor-value = { workspace = true }
tremor-common = { workspace = true }
tremor-system = { workspace = true }

[dev-dependencies]
surf = { version = "2.3", default-features = false, features = [
	"h1-client-rustls",
] }
env_logger = { workspace = true }
