[package]
name = "tremor-connectors-object-storage"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tremor-connectors.workspace = true
tremor-value.workspace = true
tremor-system.workspace = true
serde.workspace = true
thiserror.workspace = true
anyhow.workspace = true
async-trait = { version = "0.1", default-features = true }
log.workspace = true
