[package]
authors = ["The Tremor Team"]
description = "Tremor common functions"
documentation = "https://docs.rs/tremor-commons"
edition = "2021"
license = "Apache-2.0"
name = "tremor-common"
readme = "README.md"
version = "0.13.0-rc.33"

[dependencies]
tokio = { workspace = true, features = ["fs"] }
rand = { workspace = true, features = ["small_rng"] }
beef = { workspace = true, features = ["impl_serde"] }
serde = { workspace = true, features = ["derive"] }
url = { workspace = true, features = ["serde"] }
simd-json = { workspace = true, features = ["known-key"] }
simd-json-derive = { workspace = true }
base64 = { workspace = true, features = ["std"] }
regex = { workspace = true }
lazy_static = { workspace = true }
futures = { workspace = true }
pin-project-lite = { workspace = true }


[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
test-case = { workspace = true }
