[package]
authors = ["The Tremor Team"]
description = "Tremor common functions"
documentation = "https://docs.rs/tremor-commons"
edition = "2021"
license = "Apache-2.0"
name = "tremor-common"
readme = "README.md"
version = "0.13.0-rc.33"

[dependencies]
base64 = { version = "0.22", default-features = false, features = ["std"] }
beef.workspace = true
futures.workspace = true
pin-project-lite = { version = "0.2", default-features = false }
rand.workspace = true
regex.workspace = true
serde.workspace = true
simd-json.workspace = true
simd-json-derive.workspace = true
tokio.workspace = true
url.workspace = true


[dev-dependencies]
tokio.workspace = true
test-case = "3"
