name: EQC Tests for tremor-script

on: [push]

jobs:
  eqc-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Validate secret access
        run: '[ ! -z "${{secrets.EQC_LICENSE}}" ]'
      - uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
      - uses: Swatinem/rust-cache@v1
      - uses: gleam-lang/setup-erlang@v1.1.2
        with:
          otp-version: 22.3.4.9
      - name: Install deps
        run: sudo apt-get -qy update && sudo apt-get install -y libssl-dev libssl1.1
      - name: install EQC
        run: curl -O http://quviq-licencer.com/downloads/eqcR21.zip && unzip eqcR21.zip && cd Quviq* && sudo erl -noshell -eval 'eqc_install:install()' -eval 'init:stop()'
      - name: Activate EQC
        run: erl -noshell -eval 'eqc:registration("${{secrets.EQC_LICENSE}}")' -eval "eqc:start()" -eval "init:stop()"
      - name: Run
        run: make -C tremor-script
