name: Publish Docker - learn
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish Tremor Courseware Docker image to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: tremorproject/tremor
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: learn
          dockerfile: Dockerfile.learn
