name: Publish Docker - Release
on:
  release:
    types: [published]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: tremorproject/tremor
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: tremor-rs/tremor
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: tremordockerbuild
          password: ${{ secrets.GHCR_PAT }}
          registry: ghcr.io
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          repository: tremor-rs/tremor
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
