name: Publish Docker - Release
on:
  release:
    types: [published]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to GH Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: tremor-rs/tremor-runtime/tremor
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}
          tag_semver: true
          registry: docker.pkg.github.com
      - name: Publish to Docker Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: tremorproject/tremor
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true
      - name: Publish Tremor Courseware to GH Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: tremor-rs/tremor-runtime/courseware
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}
          tags: latest
          registry: docker.pkg.github.com
      - name: Publish Tremor Courseware to Docker Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: tremorproject/courseware
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest
          dockerfile: Dockerfile.learn
