name: Create release packages

on:
  release:
    types: [published]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build releases
        run: make builds
      - name: Creating release packages
        run: make packages
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: "packaging/out/*"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref }}
