name: Create release packages

on: [push]

# on:
#   release:
#     types: [published]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build releases
        run: make builds
      - name: Creating release tarballs
        run: make archives
      - name: Creating release packages
        run: make packages
