name: Validate Package Generation

on:
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]
  push:
    branches: [main]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Creating test packages
        run: make test-packages
      - name: List files
        run: ls packaging/out/*
