name: Validate Package Generation

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build releases
        run: make builds
      - name: Creating release packages
        run: make test-packages
      - name: List files
        run: ls packaging/out/*
