onramps:
  - onramp::stdin:
      pipeline: main

pipelines:
  - name: main
    steps:
      - op::count:
          metric: typed
          desc: 'events typed'
          labels:
            keyboard: mac
      - offramp::stdout
