onramps:
  - onramp::gsub:
      service_account: "./examples/gps_pubsub_secret.json"
      subscription: "projects/wf-us-dataeng-sandbox/subscriptions/wf-dataeng-test-sub"
      pipeline: main
  - onramp::stdin:
      pipeline: main

pipelines:
  - name: main
    steps:
      - offramp::gpub:
          service_account: "./examples/gps_pubsub_secret.json"  # Service Account
          topic: "projects/wf-us-dataeng-sandbox/topics/wf-dataeng-test" # topic 
          name: "tremor.txt"                                    # object name
          user_project: "wf-us-dataeng-sandbox"                 # active project
          content_encoding: "application/json"                  # content encoding
      - offramp::stdout:
          prefix: "GPUB "
