onramp:
  - id: rest
    type: rest
    preprocessors:
      - lines
    codec: json
    config:
      host: "localhost"
      port: 9000
      resources:
        - path: /write?db=test.db
          allow:
            - method: POST
              status_code: 204

offramp:
  - id: console
    type: stdout
    codec: json
  - id: rest
    type: rest
    config:
      endpoints:
        - http://localhost:8086/write?db=tremor
      headers:
        'Content-Type': 'application/json'
    codec: influx

pipeline:
  - id: demo
    interface:
      inputs:
        - in
      outputs:
        - out
    nodes:
      - id: to_influx
        op: runtime::tremor
        config:
          script: |
            match event of
                case rp = %{ body ~= influx|| } => let msg = rp.body, let msg.timestamp = system::ingest_ns(), msg
            end
    links:
      in: [ to_influx ]
      to_influx: [ out ]


binding:
  - id: default
    links:
      '/onramp/rest/{instance}/out': [ '/pipeline/demo/{instance}/in' ]
      '/pipeline/demo/{instance}/out': [ '/offramp/rest/{instance}/in', '/offramp/console/{instance}/in'  ]
#      '/pipeline/demo/{instance}/out': [ '/offramp/console/{instance}/in'  ]

mapping:
  /binding/default/01:
    instance: 01
