onramp:
  - id: rest
    type: rest
    # TODO switch to json after improving responses on invalid json
    codec: string
    config:
      host: localhost
      port: 8139
      # TODO eliminate the need for this config item
      link: true

pipeline:
  - id: main
    interface:
      inputs:
        - in
      outputs:
        - out
        - error
    nodes:
      - id: request-processing
        op: runtime::tremor
        config:
          script: |
            use std::array;
            use std::json;
            use std::url;

            # TODO add similar function to std::url for better parsing (or a url extractor)
            # functionality here is rudimentary and is here only for demo purposes
            fn parse_url(string) with
              match {"test": string} of
                case r = %{test ~= dissect|%{scheme}://%{host}/%{path}?%{query}|} =>
                  {
                    "scheme": r.test.scheme,
                    "host": r.test.host,
                    "path": "/" + url::decode(r.test.path),
                    "query": r.test.query,
                  }
                case r = %{test ~= dissect|%{scheme}://%{host}/%{path}|} =>
                  {
                    "scheme": r.test.scheme,
                    "host": r.test.host,
                    "path": "/" + url::decode(r.test.path),
                    "query": "",
                  }
                case r = %{test ~= dissect|%{scheme}://%{host}|} =>
                  {
                    "scheme": r.test.scheme,
                    "host": r.test.host,
                    "path": "/",
                    "query": "",
                  }
                default =>
                  null
              end
            end;

            # TODO add similar function to std::url for better parsing
            fn parse_query(string) with
              match {"test": string} of
                case r = %{test ~= kv|%{key}=%{val}&|} =>
                  # TODO urldecode key and value pairs
                  r.test
                default =>
                  {}
              end
            end;

            fn get_request_data(body, meta, url_parsed) with
              {
                "method": meta.request_method,
                "url": meta.request_url,
                "url_parsed": url_parsed,
                "query_parsed": parse_query(url_parsed.query),
                "headers": meta.request_headers,
                "content_type": meta.request_content_type,
                "body": body,
              }
            end;

            # for default api response
            let $response_status = 200;
            let $response_content_type = "application/json";
            let $response_headers = {
              #"content-type": "application/json",
              "x-powered-by": [ "Tremor" ],
            };

            # short-circuit for non valid requests
            let valid_methods = ["GET", "POST"];
            match array::contains(valid_methods, $request_method) of
              case true  =>
                null
              default =>
                let $response_status = 501,
                # can also name the emit port here "error" and handle
                # it same as runtime errors (which goes to "error" port too)
                # or even emit to the default port ("out"). approach here
                # is useful to track application errors though.
                emit {
                  # can use string interpolation here after fix from this issue is ported here:
                  # https://github.com/tremor-rs/tremor-runtime/issues/445
                  "error": "Method " + $request_method + " not implemented",
                  "event": event,
                } => "app-error"
            end;

            let request_url_parsed = parse_url($request_url);

            # short-circuit if url parsing failed
            match request_url_parsed of
              case null =>
                let $response_status = 500,
                emit {
                  "error": "Failed to parse the url: " + $request_url,
                  "event": event,
                } => "app-error"
              default =>
                null
            end;

            # content based on path
            let event = match request_url_parsed.path of
              case "/echo" =>
                get_request_data(event, $, request_url_parsed)

              case "/snot" =>
                "badger"

              case "/ping" =>
                let $response_status = 204,
                ""

              case "/error-test" =>
                # will throw a runtime error here
                non_existent_var

              case "/index"  =>
                let data = get_request_data(event, $, request_url_parsed),
                let name = match data.query_parsed of
                  case %{present name} => data.query_parsed.name
                  default => "world"
                end,
                let $response_content_type = "text/html",
                # TODO resolve issues of string duplication with heredoc
                #"""
                #<h1>Hello, {name}!</h1>
                #<p>Your request:</p>
                #<pre>
                #  {json::encode_pretty(data)}
                #</pre>
                #"""
                "<h1>Hello, " + name + "!</h1><p>Your request:</p><pre>" + json::encode_pretty(data) + "</pre>"

              # redirect example
              case "/" =>
                let $response_status = 301,
                let $response_headers.location = [ "/index" ],
                ""

              default =>
                let $response_status = 404,
                emit {
                  "error": "Path " + request_url_parsed.path + " not found",
                  "event": event,
                } => "app-error"
            end;

            emit event;
      - id: internal-error-processing
        op: runtime::tremor
        config:
          script: |
            let $response_status = 500;

            # can choose to not include the actual event error here, if we don't want
            # to send it back to the client
            let event.error = "Oh no, we ran into something unexpected :(\n {event.error}";

            event;
    links:
      in: [ request-processing ]

      # main request processing
      request-processing: [ out ]
      # application errors (but still succesful processing from tremor perspective)
      request-processing/app-error: [ out ]

      # tremor runtime errors
      # TODO maybe as a default, bake simple error processing directly in onramp
      # so that we can get rid of this phase and directly send errors here to onramp
      request-processing/error: [ internal-error-processing ]
      internal-error-processing: [ error ]

      # errors from the error-processing script itself
      # turtles all the way down
      internal-error-processing/error: [ error ]

binding:
  - id: default
    links:
      '/onramp/rest/{instance}/out': [ '/pipeline/main/{instance}/in' ]

      '/pipeline/main/{instance}/out': [
        # linked onramp that can respond based on pipeline output
        '/onramp/rest/{instance}/in',

        # for api debugging purposes
        #'/offramp/system::stdout/system/in'
      ]

      '/pipeline/main/{instance}/error': [
        # linked onramp that can respond based on pipeline output
        # TODO once onramps have error ports, link back to it to better distinguish
        # error events from onramp itself?
        '/onramp/rest/{instance}/in',

        # for debugging
        '/offramp/system::stderr/system/in'
      ]

      # tremor metrics
      #'/pipeline/system::metrics/system/out': [ '/offramp/system::stdout/system/in' ]
mapping:
  /binding/default/01:
    instance: '01'
