onramp:
  - id: rest
    type: rest
    codec: "string"
    config:
      host: localhost
      port: 8139

pipeline:
  - id: main
    interface:
      inputs:
        - in
      outputs:
        - out
        - error
    nodes:
      - id: runtime
        op: runtime::tremor
        config:
          script: |
            {
              "method": $request_method,
              "url": $request_url,
              "headers": $request_headers,
              "content_type": $request_content_type,
              "body": event,
            }
    links:
      in: [ runtime ]
      runtime: [ out ]
      runtime/error: [ error ]

offramp:
  - id: console
    type: stdout
    #postprocessors:
    #  - lines

binding:
  - id: rest
    links:
      '/onramp/rest/{instance}/out': [ '/pipeline/main/{instance}/in' ]
      '/pipeline/main/{instance}/out': [ '/offramp/console/{instance}/in' ]
      '/pipeline/main/{instance}/error': [ '/offramp/system::stderr/system/in' ]

mapping:
  /binding/rest/01:
    instance: "01"
