onramp:
  - id: rest
    type: rest
    linked: true
    codec: string
    config:
      host: localhost
      port: 9139

pipeline:
  - id: main
    interface:
      inputs:
        - in
        - in-errors
        - from-offramp
      outputs:
        - out
        - error
        - to-onramp
    nodes:
      - id: request-processing
        op: runtime::tremor
        config:
          script: |
            # TODO if we provide parsed uri parts as meta variables, this logic will be
            # simpler here (just need to override request_host)
            match {"test": $request_url} of
              case r = %{test ~= dissect|%{scheme}://%{host}/%{path_and_rest}|} =>
                let $endpoint = "{r.test.scheme}://localhost:8139/{r.test.path_and_rest}"
              default =>
                null
            end;
            event;
      - id: response-processing
        op: runtime::tremor
        config:
          script: |
            use std::array;

            let $response_headers.x-powered-by = match $response_headers of
              # TODO standardize on string type for header values (even with multiple entries)?
              case %{present x-powered-by, x-powered-by ~= %[]}  =>
                array::push($response_headers.x-powered-by, "Tremor (As Proxy)")
              case %{present x-powered-by}  =>
                let $response_headers.x-powered-by = [ $response_headers.x-powered-by, "Tremor (As Proxy)" ]
              default =>
                let $response_headers.x-powered-by = [ "Tremor (As Proxy)" ]
            end;

            # if we want to overide the content-type sent as part of the offramp response
            # TODO currently content type in headers has more priority. revisit?
            #let $response_content_type = "text/plain";

            event;
      - id: internal-error-processing
        op: runtime::tremor
        config:
          script: |
            let $response_status = 500;

            # can choose to not include the actual event error here, if we don't want
            # to send it back to the client
            let event.error = "Oh no, we ran into something unexpected :(\n {event.error}";

            event;

    links:
      # all pipeline inputs
      in: [ request-processing ]
      in-errors: [ internal-error-processing ]
      from-offramp: [ response-processing ]

      request-processing: [ out ]

      response-processing: [ to-onramp ]

      # tremor runtime errors
      # TODO maybe as a default, bake simple error processing directly in onramp
      # so that we can get rid of this phase and directly send errors here to onramp
      request-processing/error: [ internal-error-processing ]
      response-processing/error: [ internal-error-processing ]
      internal-error-processing: [ error ]

offramp:
  - id: upstream
    type: rest
    linked: true
    codec: string
    config:
      # TODO make this optional too
      endpoints:
       - http://localhost:8139/snot
      #method: "PUT"
      #headers:
      #  "Client": "Tremor"

binding:
  - id: default
    links:
      '/onramp/rest/{instance}/out': [ '/pipeline/main/{instance}/in' ]
      # this can go to a separate pipeline too
      '/onramp/rest/{instance}/error': [ '/pipeline/main/{instance}/in-errors' ]

      '/pipeline/main/{instance}/out': [
        '/offramp/upstream/{instance}/in',
        #'/offramp/system::stdout/system/in' # for debugging
      ]

      '/pipeline/main/{instance}/error': [ '/offramp/system::stderr/system/in' ]

      # linked offramp that send responses to a pipeline
      '/offramp/upstream/{instance}/out': [ '/pipeline/main/{instance}/from-offramp' ]
      '/pipeline/main/{instance}/to-onramp': [
        # linked onramp that can respond based on pipeline output
        '/onramp/rest/{instance}/response',
        # for debugging purposes
        '/offramp/system::stdout/system/in'
      ]

      '/pipeline/main/{instance}/error': [
        # linked onramp that can respond based on pipeline output
        # TODO once onramps have error ports, link back to it to better distinguish
        # error events from onramp itself?
        '/onramp/rest/{instance}/response',

        # for debugging
        '/offramp/system::stderr/system/in'
      ]

      # linked offramp that send responses to a pipeline
      '/offramp/upstream/{instance}/response': [ '/pipeline/main/{instance}/from-offramp' ]
      # this can go to a separate pipeline too
      '/offramp/upstream/{instance}/error': [ '/pipeline/main/{instance}/in-errors' ]

      # tremor metrics
      #'/pipeline/system::metrics/system/out': [ '/offramp/system::stdout/system/in' ]
mapping:
  /binding/default/01:
    instance: '01'
