onramp:
  - id: rest
    type: rest
    config:
      host: localhost
      port: 8139

pipeline:
  - id: main
    interface:
      inputs:
        - in
      outputs:
        - out
        - error
    nodes:
      - id: runtime
        op: runtime::tremor
        config:
          script: |
            {
              "method": $method,
              "path": $path,
              "query": $query,
              "headers": $headers,
              "body": event,
            }
    links:
      in: [ runtime ]
      runtime: [ out ]
      runtime/error: [ error ]

offramp:
  - id: console
    type: stdout
    #postprocessors:
    #  - lines

binding:
  - id: rest
    links:
      '/onramp/rest/{instance}/out': [ '/pipeline/main/{instance}/in' ]
      '/pipeline/main/{instance}/out': [ '/offramp/console/{instance}/in' ]
      '/pipeline/main/{instance}/error': [ '/offramp/system::stderr/system/in' ]

mapping:
  /binding/rest/01:
    instance: "01"
