---
onramps:
  - onramp::kafka:
      group_id: demo
      topics:
        - demo
      brokers:
        - kafka:9092
      pipeline: main
pipelines:
  - name: main
    subpipelines:
      - name: info
        steps:
          - offramp::kafka:
              brokers:
                - kafka:9092
              topic: info
      - name: error
        steps:
          - offramp::kafka:
              brokers:
                - kafka:9092
              topic: error
      - name: default
        steps:
          - offramp::kafka:
              brokers:
                - kafka:9092
              topic: default
    steps:
      - parse::json
      - classifier::tremor:
          rules:
            - class: 'info'
              rule: 'short_message:"info"'
            - class: 'error'
              rule: 'short_message:"ERROR"'
      - render::json
      - op::route:
          var: classification
          vals:
            - error
            - info
          outputs:
            - sub::error
            - sub::info
      - sub::default
