onramp:
  - id: udp
    type: udp
    preprocessors:
      - decompress
      - gelf-chunking
      - decompress
    codec: json
    config:
      host: 0.0.0.0
      port: 9000

offramp:
  - id: console
    type: rest
    config:
      endpoints:


binding:
  - id: udp
    links:
      '/onramp/udp/{instance}/out': [ '/pipeline/main/{instance}/in' ]
      '/pipeline/main/{instance}/out': [ '/offramp/console/{instance}/in' ]

mapping:
  /binding/udp/01:
    instance: "01"

pipeline:
  - id: main
    interface:
      inputs:
        - in
      outputs:
        - out
      node:
        - id: batch
          type: batc
    links:
      in: [ out ]
