onramp:
  - id: ws
    type: ws
    codec: string
    preprocessors:
      # TODO lines pre-processor no longer working here (for first connection). investigate
      - lines
    config:
      host: localhost
      port: 8139
      # TODO move this to top level
      link: true

# TODO switch to trickle for this
pipeline:
  - id: main
    interface:
      inputs:
        - in
      outputs:
        - out
        - error
    nodes:
      - id: runtime
        op: runtime::tremor
        config:
          script: |
            match event of
              # snot is a special snowflake
              case "snot\n" => "badger"
              # TODO remove after resolving preprocessor issue for above
              default => "hello from local proxy"
              #default => event
            end
    links:
      in: [ runtime ]
      runtime: [ out ]
      runtime/error: [ error ]

binding:
  - id: default
    links:
      '/onramp/ws/{instance}/out': [ '/pipeline/main/{instance}/in' ]

      '/pipeline/main/{instance}/out': [
        # linked onramp that can reply based on pipeline output
        '/onramp/ws/{instance}/in',

        # for api debugging purposes
        '/offramp/system::stdout/system/in'
      ]

      '/pipeline/main/{instance}/error': [ '/offramp/system::stderr/system/in' ]

      # tremor metrics
      #'/pipeline/system::metrics/system/out': [ '/offramp/system::stdout/system/in' ]
mapping:
  /binding/default/01:
    instance: '01'
