onramp:
  - id: ws
    type: ws
    linked: true
    codec: string
    preprocessors:
      # TODO lines pre-processor no longer working here (for first connection). investigate
      - lines
    config:
      host: localhost
      port: 9139

pipeline:
  - id: main
    interface:
      inputs:
        - in
        - from-offramp
      outputs:
        - out
        - to-onramp
    links:
      in: [ out ]
      from-offramp: [ to-onramp ]

offramp:
  - id: upstream
    type: ws
    linked: true
    codec: string
    postprocessors:
      - lines
    config:
      url: "ws://echo.websocket.org"
      # with local server
      #url: "ws://localhost:8139"

binding:
  - id: default
    links:
      '/onramp/ws/{instance}/out': [ '/pipeline/main/{instance}/in' ]
      '/pipeline/main/{instance}/out': [
        '/offramp/upstream/{instance}/in',
        #'/offramp/system::stdout/system/in' # for debugging
      ]

      '/pipeline/main/{instance}/error': [ '/offramp/system::stderr/system/in' ]

      # linked offramp that send responses to a pipeline
      '/offramp/upstream/{instance}/response': [ '/pipeline/main/{instance}/from-offramp' ]
      '/pipeline/main/{instance}/to-onramp': [
        # linked onramp that can respond based on pipeline output
        '/onramp/ws/{instance}/response',
        # for debugging purposes
        '/offramp/system::stdout/system/in'
      ]

      # tremor metrics
      #'/pipeline/system::metrics/system/out': [ '/offramp/system::stdout/system/in' ]

mapping:
  /binding/default/01:
    instance: '01'
