[package]
authors = ["The Tremor Team"]
name = "tremor-value"
description = "Tremor Value"
documentation = "https://docs.rs/tremor-value"
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22"
beef = "0.5"
halfbrown = { workspace = true }
serde = { workspace = true }
simd-json = { workspace = true }
simd-json-derive = { workspace = true }
value-trait = { workspace = true }
tremor-common = { workspace = true }

[dev-dependencies]
float-cmp = "0.10"
getopts = "0.2"
proptest = "1.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
128bit = ["simd-json/128bit"]
