[package]
authors = ["The Tremor Team"]
description = "Tremor Script Interpreter"
documentation = "https://docs.rs/tremor-script"
edition = "2021"
license = "Apache-2.0"
name = "tremor-value"
readme = "README.md"
repository = "https://github.com/tremor-rs/tremor-runtime"
version = "0.13.0-rc.33"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = { workspace = true }
beef = { workspace = true }
halfbrown = { workspace = true }
serde = { workspace = true }
simd-json = { workspace = true }
simd-json-derive = { workspace = true }
value-trait = { workspace = true, features = ["custom-types"] }
tremor-common = { workspace = true }

[dev-dependencies]
float-cmp = { workspace = true }
getopts = { workspace = true }
proptest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[features]
128bit = []
